services:
  agenda-api:
    build: .
    container_name: agenda-api
    env_file:
      - .env.prod
    restart: always
    depends_on:
      mongo:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - proxy
      - internal
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy" 
      - "traefik.http.routers.agenda.rule=Host(`agenda-api.angelite.lat`)"
      - "traefik.http.routers.agenda.entrypoints=websecure"
      - "traefik.http.routers.agenda.tls=true"
      - "traefik.http.routers.agenda.tls.certresolver=letsencrypt"
      - "traefik.http.services.agenda.loadbalancer.server.port=3000"

  mongo:
    image: mongo:7
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db
    command: ["--replSet", "rs0", "--bind_ip_all"]

    networks:
      - internal
    healthcheck:
      test: >
        mongosh --eval "try { rs.status() } catch (e) { rs.initiate({ _id: 'rs0', members: [{ _id: 0, host: 'mongo:27017' }] }) }"
      interval: 5s
      timeout: 10s
      retries: 10
      start_period: 10s

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    volumes:
      - redis-data:/data
    networks:
      - internal
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  mongo-data:
  redis-data:

networks:
  proxy:
    external: true
  internal:
    driver: bridge

